services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: services/catalog/Catalog.API/Dockerfile
    ports:
        - "8000:8000"
    depends_on:
        - CatalogDB
    environment:
        - ASPNETCORE_URLS=http://+:8000
        - DatabaseSettings__ConnectionString=mongodb://CatalogDB:27017
        - DatabaseSettings__DatabaseName=CatalogDB
        - DatabaseSettings__ProductsCollection=Products
        - DatabaseSettings__BrandsCollection=Brands
        - DatabaseSettings__TypesCollection=Types

  CatalogDB:
    image: mongo
    container_name: CatalogDB
    ports:
        - "27017:27017"
    volumes:
        - catalogdbdata:/data/db
volumes:
  catalogdbdata:
